#default: &default
#  adapter: postgresql
#  encoding: unicode
#  pool: 5
#  host: localhost
#  username: pguser
#  password: E@ten234
#production:
#  <<: *default
#  database: coldNoses_production
#  username: coldNoses
#  password: <%= ENV['COLDNOSES_DATABASE_PASSWORD'] %>
default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3


test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: db/production.sqlite3"
